server:
  port: 8082

spring:
  application:
    name: micro-weather-config-client
  cloud:
    config:
      profile: dev
      uri: http://locahost:8081/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/