server:
  port: 8083

spring:
  application:
    name: wsa-weather-report-eureka-feign-gateway
  thymeleaf:
    cache: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      feignName:
        connectionTimeout: 5000
        readTimeout: 5000