server:
  port: 8081

spring:
  application:
    name: micro-weather-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/junral/SpringCloud-Microservices-Development
          searchPaths: config-repo

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/